In [1]:
import open3d as o3d
import numpy as np
from copy import deepcopy

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [4]:
def draw_centers(centers, radius, color):
    spheres = []
    sphere_radius = radius 
    
    for point in centers:
        mesh_sphere = o3d.geometry.TriangleMesh.create_sphere(radius=sphere_radius)
        mesh_sphere.compute_vertex_normals()
        
        mesh_sphere.translate(point)
        
        spheres.append(mesh_sphere)
    
    all_spheres = o3d.geometry.TriangleMesh()
    for sphere in spheres:
        all_spheres += sphere
    
    all_spheres.paint_uniform_color(color) 
    
    o3d.visualization.draw_geometries([all_spheres])

In [5]:
def draw_multiple_centers(center_sets, radius, colors):
    all_geometries = []
    
    for centers, radius, color in zip(center_sets, radius, colors):
        spheres = []
        for point in centers:
            mesh_sphere = o3d.geometry.TriangleMesh.create_sphere(radius=radius)
            mesh_sphere.compute_vertex_normals()
            mesh_sphere.translate(point)
            mesh_sphere.paint_uniform_color(color)
            spheres.append(mesh_sphere)
        
        # Combine all spheres for this set into one mesh (optional, for efficiency)
        combined_mesh = o3d.geometry.TriangleMesh()
        for sphere in spheres:
            combined_mesh += sphere
        
        all_geometries.append(combined_mesh)
    
    # Visualize all geometries together
    o3d.visualization.draw_geometries(all_geometries)

In [138]:
centers_number = 4000
center_datas = []
for i in range(1, 8):
    center_filename = fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-{centers_number}/dynamic_mesh_0res_{centers_number}_{i:03d}.xyz'
    center_data = np.loadtxt(center_filename)
    center_datas.append(center_data)

center0 = center_datas[0]
print(center0, center0.__len__())

[[-6.5728414e-01 -2.2804592e+00  1.4319637e-01]
 [-6.5891594e-01 -2.2351038e+00  1.5657887e+00]
 [-3.7024853e-01 -3.0614653e-01  6.0015520e-01]
 ...
 [-2.5733600e-01  2.7517327e-03  7.8661865e-01]
 [-6.7332757e-01 -2.8276653e+00  1.4175950e+00]
 [-6.4990807e-01 -1.8400391e+00 -2.2744595e-01]] 4000


In [154]:
centers_number = 4000 - 5 - 5
center_datas = []
for i in range(1, 8):
    center_filename = fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000/impr/dynamic_mesh_0impr_{centers_number}_{i:03d}.xyz'
    center_data = np.loadtxt(center_filename)
    center_datas.append(center_data)

center0 = center_datas[0]
print(center0, center0.__len__())

[[-0.6568455  -2.2798455   0.14834443]
 [-0.66031826 -2.233       1.5618951 ]
 [-0.3705576  -0.30405605  0.60026544]
 ...
 [-0.2613254   0.00564304  0.7871034 ]
 [-0.66861194 -2.823609    1.4162824 ]
 [-0.64963084 -1.8318919  -0.22327408]] 3990


In [157]:
draw_centers(center_datas[0], radius=0.02, color=[0.4, 0.4, 0.4])

In [147]:
radii = [0.03, 0.03]
colors = [(0.4, 0.4, 0.4), (1, 0, 0)]

draw_multiple_centers([center_datas[0], center_datas[3]], radii, colors)

In [152]:
import numpy as np

movement_threshold = 0.02
centers_number = 4000
center_datas = []
for i in range(1, 8):
    center_filename = fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-{centers_number}/mesh_0res_{centers_number}_{i:03d}.xyz'
    center_data = np.loadtxt(center_filename)
    center_datas.append(center_data)


num_frames = len(center_datas)
num_centers = len(center_datas[0]) 


low_movement_centers = []
high_movement_centers = []


for center_idx in range(num_centers):
    total_movement = 0

    for frame_idx in range(num_frames - 1):
        displacement = np.linalg.norm(center_datas[frame_idx + 1][center_idx] - center_datas[frame_idx][center_idx])
        total_movement += displacement


    if total_movement < movement_threshold:
        low_movement_centers.append(center_idx)
    else:
        high_movement_centers.append(center_idx)

print("Centers with low movement:", low_movement_centers, len(low_movement_centers))
print("Centers with high movement:", high_movement_centers, len(high_movement_centers))

static_centers = []
dynamic_centers = []
for i in low_movement_centers:
    static_centers.append(center_datas[0][i])
for i in high_movement_centers:
    dynamic_centers.append(center_datas[0][i])


Centers with low movement: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 16, 17, 18, 19, 21, 22, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 84, 86, 87, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 103, 104, 105, 106, 109, 110, 111, 112, 113, 114, 115, 116, 119, 120, 121, 122, 123, 124, 125, 126, 127, 130, 132, 133, 134, 136, 137, 138, 139, 140, 141, 145, 146, 147, 148, 149, 151, 152, 153, 154, 155, 157, 158, 159, 160, 164, 165, 166, 167, 168, 170, 171, 172, 173, 174, 176, 177, 179, 180, 182, 183, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 244, 245, 246, 247, 248, 250, 251,

In [19]:
draw_centers(dynamic_centers, radius=0.03, color=[1, 0, 0])

In [153]:
radii = [0.03, 0.03]
colors = [(0.4, 0.4, 0.4), (1, 0, 0)]

draw_multiple_centers([static_centers, dynamic_centers], radii, colors)

In [86]:
import open3d as o3d
import numpy as np
def get_selected_parts(mesh, dynamic_indices, static_indices):
    selected_vertex_indices = dynamic_indices 
    
    vertices = np.asarray(mesh.vertices)
    triangles = np.asarray(mesh.triangles)
    selected_indices_set = set(selected_vertex_indices)
    
    new_vertex_indices = {}
    new_index_counter = 0
    
    new_vertices = []
    new_triangles = []
    
    for tri in triangles:
        in_selected = [v in selected_indices_set for v in tri]
        if sum(in_selected) >= 1: 
            new_triangle = []
            for v in tri:
                if v not in new_vertex_indices:
                    new_vertex_indices[v] = new_index_counter
                    new_vertices.append(vertices[v])
                    new_index_counter += 1
                new_triangle.append(new_vertex_indices[v])
            new_triangles.append(new_triangle)
    
    dynamic_mesh = o3d.geometry.TriangleMesh(
        vertices=o3d.utility.Vector3dVector(new_vertices),
        triangles=o3d.utility.Vector3iVector(new_triangles)
    )
    
    dynamic_mesh.compute_vertex_normals()
    
    dynamic_mesh.paint_uniform_color([1, 0, 0])
    
    #static_mesh = mesh.select_by_index(static_indices)
    selected_vertex_indices = static_indices 
    
    vertices = np.asarray(mesh.vertices)
    triangles = np.asarray(mesh.triangles)
    selected_indices_set = set(selected_vertex_indices)
    
    new_vertex_indices = {}
    new_index_counter = 0
    
    new_vertices = []
    new_triangles = []
    
    for tri in triangles:
        in_selected = [v in selected_indices_set for v in tri]
        if sum(in_selected) >= 1: 
            new_triangle = []
            for v in tri:
                if v not in new_vertex_indices:
                    new_vertex_indices[v] = new_index_counter
                    new_vertices.append(vertices[v])
                    new_index_counter += 1
                new_triangle.append(new_vertex_indices[v])
            new_triangles.append(new_triangle)
    
    static_mesh = o3d.geometry.TriangleMesh(
        vertices=o3d.utility.Vector3dVector(new_vertices),
        triangles=o3d.utility.Vector3iVector(new_triangles)
    )
    
    static_mesh.compute_vertex_normals()
    static_mesh.paint_uniform_color([0.4, 0.4, 0.4])
    
    
    
    return dynamic_mesh, static_mesh

In [115]:
for i in range(1, 8):
    centers_i = o3d.geometry.PointCloud()
    centers_i.points = o3d.utility.Vector3dVector(center_datas[i-1])
    centers_i_tree = o3d.geometry.KDTreeFlann(centers_i)
    
    mesh = o3d.io.read_triangle_mesh(fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene/mesh_000{i:1}.obj')
    mesh.compute_vertex_normals()
    vertices = np.array(mesh.vertices)
    triangles = np.array(mesh.triangles)
    
    static_indices = []
    dynamic_indices = []
    
    for j in range(len(vertices)):
        [k, index, _] = centers_i_tree.search_knn_vector_3d(vertices[j], 1)
        
        if index[0] in low_movement_centers:  
            static_indices.append(j)
        else:
            dynamic_indices.append(j)
    
    dynamic_mesh, static_mesh = get_selected_parts(mesh, dynamic_indices, static_indices)
    #o3d.visualization.draw_geometries([dynamic_mesh, static_mesh])
    o3d.io.write_triangle_mesh(fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene\Dynamic/dynamic_mesh_0{i:03}.obj', dynamic_mesh, write_vertex_normals=False, write_vertex_colors=False, write_triangle_uvs=False)
    o3d.io.write_triangle_mesh(fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene\Static/static_mesh_0{i:03}.obj', static_mesh, write_vertex_normals=False, write_vertex_colors=False, write_triangle_uvs=False)

[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.


In [159]:
import os

output_folder = r"G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000"
os.makedirs(output_folder, exist_ok=True) 

for i in range(1, 8):
    # File names
    dynamic_centers = os.path.join(output_folder, f"dynamic_mesh_0res_4000_{i:03}.xyz")
    coarse_centers = os.path.join(output_folder, f"mesh_0res_4000_{i:03}.xyz")
    output_file = os.path.join(output_folder, f"combined_mesh_0res_4000_{i:03}.xyz")
    
    if not os.path.exists(dynamic_centers) or not os.path.exists(coarse_centers):
        print(f"Skipping {i:03}: One of the files is missing.")
        continue
    
    with open(output_file, "w") as outfile:
        with open(dynamic_centers, "r") as dfile:
            outfile.write(dfile.read())
        
        with open(coarse_centers, "r") as sfile:
            outfile.write(sfile.read())
    
    print(f"Combined files for index {i:03} into {output_file}.")

Combined files for index 001 into G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000\combined_mesh_0res_4000_001.xyz.
Combined files for index 002 into G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000\combined_mesh_0res_4000_002.xyz.
Combined files for index 003 into G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000\combined_mesh_0res_4000_003.xyz.
Combined files for index 004 into G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000\combined_mesh_0res_4000_004.xyz.
Combined files for index 005 into G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000\combined_mesh_0res_4000_005.xyz.
Combined files for index 006 into G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000\combined_mesh_0res_4000_006.xyz.
Combined files for index 007 into G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000\combined_mesh_0res_4000_007.xyz.


In [160]:
centers_number = 4000
combined_center_datas = []
for i in range(1, 8):
    center_filename = fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene-max-4000/combined_mesh_0res_4000_{i:03d}.xyz'
    center_data = np.loadtxt(center_filename)
    combined_center_datas.append(center_data)

center0 = combined_center_datas[0]
print(center0, center0.__len__())

[[-0.65728414 -2.2804592   0.14319637]
 [-0.65891594 -2.2351038   1.5657887 ]
 [-0.37024853 -0.30614653  0.6001552 ]
 ...
 [-0.02579837  2.6158857   0.57067585]
 [-0.70234305  0.20056649  0.9193859 ]
 [-0.21681708  1.5670214   0.49613115]] 8000


In [164]:
draw_centers(combined_center_datas[5], radius=0.03, color=[0.4, 0.4, 0.4])

In [169]:
reference_mesh = o3d.io.read_triangle_mesh(r"G:\VS2022Projects\arap-volume-tracking-main\data\scene\Dynamic/dynamic_mesh_0003.obj")
print(reference_mesh)
reference_mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([reference_mesh])


TriangleMesh with 20456 points and 36683 triangles.


In [170]:
load_reference_mesh_trimesh = reference_mesh

print(np.array(load_reference_mesh_trimesh.vertices).__len__())
decimated_reference_mesh = o3d.geometry.TriangleMesh.simplify_quadric_decimation(load_reference_mesh_trimesh, 9000, boundary_weight= 8000)
print(decimated_reference_mesh)

subdivided_mesh = o3d.geometry.TriangleMesh.subdivide_midpoint(decimated_reference_mesh, number_of_iterations=1)
print(subdivided_mesh)
o3d.io.write_triangle_mesh(fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene\Dynamic/decimated_reference_mesh.obj', decimated_reference_mesh, write_vertex_normals=False, write_vertex_colors=False, write_triangle_uvs=False)
o3d.io.write_triangle_mesh(fr'G:\VS2022Projects\arap-volume-tracking-main\data\scene\Dynamic/subdivided_reference_mesh.obj', subdivided_mesh, write_vertex_normals=False, write_vertex_colors=False, write_triangle_uvs=False)


20456
TriangleMesh with 6561 points and 9000 triangles.
TriangleMesh with 22147 points and 36000 triangles.
[Open3D WARNING] Write OBJ can not include triangle normals.
[Open3D WARNING] Write OBJ can not include triangle normals.


True